version: '3'
services:
  front-envoy:
    image: envoyproxy/envoy:v1.26-latest
    ports:
      - "8080:8080"
      - "9900:9902"
    volumes:
      - ./front-envoy/front.yaml:/etc/envoy/envoy.yaml
    command:
      - "--config-path /etc/envoy/envoy.yaml"
      - "-l debug"
    depends_on:
      - eth-proxy-getblock
      - eth-proxy-alchemy
      - eth-proxy-infura
      - eth-proxy-quicknode

  eth-proxy-getblock:
    image: envoyproxy/envoy:v1.26-latest
    # ports:
    #   - "8084:8080"
    #   - "9904:9902"
    volumes:
      - ./eth/getblock.yaml:/etc/envoy/envoy.yaml
    command:
      - "--config-path /etc/envoy/envoy.yaml"
      - "-l debug"

  eth-proxy-alchemy:
    image: envoyproxy/envoy:v1.26-latest
    # ports:
    #   - "8081:8080"
    #   - "9901:9902"
    volumes:
      - ./eth/alchemy.yaml:/etc/envoy/envoy.yaml
    command:
      - "--config-path /etc/envoy/envoy.yaml"
      - "-l debug"

  eth-proxy-infura:
    image: envoyproxy/envoy:v1.26-latest
    # ports:
    #   - "8082:8080"
    #   - "9902:9902"
    volumes:
      - ./eth/infura.yaml:/etc/envoy/envoy.yaml
    command:
      - "--config-path /etc/envoy/envoy.yaml"
      - "-l debug"

  eth-proxy-quicknode:
    image: envoyproxy/envoy:v1.26-latest
    # ports:
    #   - "8083:8080"
    #   - "9903:9902"
    volumes:
      - ./eth/quicknode.yaml:/etc/envoy/envoy.yaml
    command:
      - "--config-path /etc/envoy/envoy.yaml"
      - "-l debug"