# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = 2048
    vb.cpus = 1
  end

  # config.disksize.size = ENV['DISK_MEMORY']

  config.vm.define "main" do |main|
    main.vm.hostname = "main"

    main.vm.network "private_network", type: "dhcp"

    main.vm.provision "ansible" do |a|
      a.verbose = "v"
      a.playbook = "../ansible/setup_server.yaml"
      a.groups = {
        "vms" => ["main"]
      }
    end
  end

  config.vm.define "front" do |front|
    front.vm.hostname = "front-envoy"

    front.vm.network "private_network", type: "dhcp"

    front.vm.provision "ansible" do |a|
      a.verbose = "v"
      a.playbook = "../ansible/setup_client.yaml"
      a.groups = {
        "vms" => ["front"]
      }
    end
  end

  config.vm.define "proxy" do |proxy|
    proxy.vm.hostname = "eth-proxy-getblock"

    proxy.vm.network "private_network", type: "dhcp"

    proxy.vm.provision "ansible" do |a|
      a.verbose = "v"
      a.playbook = "../ansible/setup_client.yaml"
      a.groups = {
        "vms" => ["proxy"]
      }
    end

    # proxy.vm.synced_folder "~/great-proxy", "/home/vagrant/great-proxy", create: true
  end
end