# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = 2048
    vb.cpus = 1
  end

  # config.disksize.size = ENV['DISK_MEMORY']

  config.vm.define "main" do |main|
    main.vm.hostname = "main"

    main.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "front" do |front|
    front.vm.hostname = "front-envoy"

    front.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "proxy1" do |proxy|
    proxy.vm.hostname = "proxy1"

    proxy.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "proxy2" do |proxy|
    proxy.vm.hostname = "proxy2"

    proxy.vm.network "private_network", type: "dhcp"
  end

  config.vm.provision "ansible" do |a|
    a.verbose = "v"
    a.playbook = "../ansible/setup.yaml"
    a.groups = {
      "vms:children" => ["servers", "clients", "proxy"],
      "servers"      => ["main"],
      "clients"      => ["front", "proxy1", "proxy2"],
      "proxy"        => ["proxy1", "proxy2"]
    }
  end
end