# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = 2048

    vb.cpus = 1
  end

  # config.disksize.size = ENV['DISK_MEMORY']

  config.vm.define "main" do |main|
    main.vm.hostname = "main"

    main.vm.network "private_network", type: "dhcp"

    # main.vm.synced_folder "~/great-proxy", "/home/vagrant/great-proxy", create: true
  end

  config.vm.define "front" do |front|
    front.vm.hostname = "front-envoy"

    front.vm.network "private_network", type: "dhcp"

    # front.vm.synced_folder "~/great-proxy", "/home/vagrant/great-proxy", create: true
  end

  config.vm.define "proxy" do |proxy|
    proxy.vm.hostname = "eth-proxy-getblock"

    proxy.vm.network "private_network", type: "dhcp"


    # proxy.vm.synced_folder "~/great-proxy", "/home/vagrant/great-proxy", create: true
  end

  config.vm.provision "shell", path: "./bootstrap.sh"
end